[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.cronos]
rpc_url = "https://evm-t3.cronos.org/"
chain_id = 338

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
